version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          command: ./gradlew clean
      - run:
          command: ./gradlew :app:assembleDebug :feature_product:assembleDebug lintDebug
      - run:
          command: ./gradlew detekt
      - run:
          command: ./gradlew spotlessCheck
      - run:
          command: ./gradlew testDebug
      - run:
          command: ./gradlew assembleDebug