version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          command: ./gradlew clean
      - run:
          command: ./gradlew lintKotlin
      - run:
          command: ./gradlew assembleDebug
